<?php

namespace AppBundle\Repository;

/**
 * LearnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LearnerRepository extends \Doctrine\ORM\EntityRepository
{
}
