<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRepository extends EntityRepository
{
    /**
     * @param \DateTime $week
     * @param integer $motherId
     * @param integer|null $subjectId
     * @return array
     */
    public function findByParentsAndSubject(\DateTime $week, $motherId, $subjectId = null)
    {
        $queryBuilder = $this->createQueryBuilder('mark');

        // Filter by mother
        $queryBuilder
            ->join('mark.learner', 'learner', 'WITH', 'learner.mother = :motherId')
            ->where('mark.created >= :startWeekDate')
            ->setParameters([
                'motherId' => $motherId,
                'startWeekDate' => $week
            ]);

        // If we need filter by subject
        if (!is_null($subjectId)) {
            $queryBuilder->andWhere('mark.subject = :subjectId');
            $queryBuilder->setParameter('subjectId', $subjectId);
        }

        return $queryBuilder
            ->orderBy('mark.created', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
