<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRepository extends EntityRepository
{
    /**
     * @param \DateTime $week
     * @param integer $motherId
     * @param string $order
     * @return array
     */
    public function findByParentsAndSubject(\DateTime $week, $motherId, $order)
    {
        $queryBuilder = $this->createQueryBuilder('mark');

        // Filter by mother
        $queryBuilder
            ->join('mark.learner', 'learner', 'WITH', 'learner.mother = :motherId')
            ->join('mark.subject', 'subject')
            ->where('mark.created >= :startWeekDate')
            ->setParameters([
                'motherId' => $motherId,
                'startWeekDate' => $week
            ]);

        return $queryBuilder
            ->orderBy('subject.title', $order)
            ->getQuery()
            ->getResult();
    }
}
