<?php

namespace AppBundle\Repository;

/**
 * MarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByParentsAndSubject(\DateTime $week, $parentsId, $subjectId = null)
    {
        $queryBuilder = $this->createQueryBuilder('mark');

        // Здесь отсев по родителю
        $queryBuilder
            ->join('mark.learner', 'learner', 'WITH', 'learner.parents = :parents_id')
            ->where('mark.created >= :start_week_date')
            ->setParameters([
                'parents_id' => $parentsId,
                'start_week_date' => $week
            ]);

        // Если необходимо фильтровать по предмету
        if (!is_null($subjectId)) {
            $queryBuilder->andWhere('mark.subject = :subject_id');
            $queryBuilder->setParameter('subject_id', $subjectId);
        }

        return $queryBuilder
            ->orderBy('mark.created', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
